AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: izumo

Parameters:
  ScheduleExpression:
    Description: when you stop instances (default is 22:00 JST)
    Type: String
    Default: cron(0 13 ? * MON-FRI *)

Resources:
  IzumoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Description: "Stop EC2/RDS/ASG instances and ECS tasks"
      Handler: index.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      MemorySize: 128
      Timeout: 60
      Policies:
      - Statement:
        - Sid: DescribeAndExecuteStop
          Effect: Allow
          Action:
          - ec2:DescribeInstances
          - ec2:StopInstances
          - ecs:ListClusters
          - ecs:ListServices
          - ecs:ListTasks
          - ecs:StopTask
          - ecs:UpdateService
          - rds:DescribeDBInstances
          - rds:StopDBInstance
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:UpdateAutoScalingGroup
          Resource: '*'
      Events:
        CloudWatchEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression